version: '3.4'  # Adjust the version based on Docker Compose version compatibility

services:
  web:
    build: ./apartments_web
    ports:
      - "3000:3000"
    volumes:
      - ./apartments_web:/app
    depends_on:
      - backend

  backend:
    build: ./apartments_be
    ports:
      - "9000:9000"
    volumes:
      - ./apartments_be:/app